# Generated by Django 4.1.2 on 2022-10-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=True),
        ),
    ]
